// <auto-generated />
using System;
using Course_Work.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Course_work.Migrations
{
    [DbContext(typeof(EsportsDbContext))]
    partial class EsportsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Course_Work.Models.Game", b =>
                {
                    b.Property<int>("ID_Games")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Games");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Games"));

                    b.Property<string>("Jenre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Platform")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Release_year")
                        .HasColumnType("int");

                    b.HasKey("ID_Games");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Course_Work.Models.GamesNews", b =>
                {
                    b.Property<int>("ID_Games_News")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Games_News");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Games_News"));

                    b.Property<int>("ID_Games")
                        .HasColumnType("int")
                        .HasColumnName("ID_Games");

                    b.Property<int>("ID_News")
                        .HasColumnType("int")
                        .HasColumnName("ID_News");

                    b.HasKey("ID_Games_News");

                    b.HasIndex("ID_Games");

                    b.HasIndex("ID_News");

                    b.ToTable("Games_News");
                });

            modelBuilder.Entity("Course_Work.Models.Match", b =>
                {
                    b.Property<int>("ID_Matches")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Matches");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Matches"));

                    b.Property<int>("ID_Tournament")
                        .HasColumnType("int")
                        .HasColumnName("ID_Tournament");

                    b.Property<DateTime>("Match_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Score")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_Matches");

                    b.HasIndex("ID_Tournament");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Course_Work.Models.News", b =>
                {
                    b.Property<int>("ID_News")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_News");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_News"));

                    b.Property<DateTime>("Date_of_publication")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Time_of_publication")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ID_News");

                    b.ToTable("News");
                });

            modelBuilder.Entity("Course_Work.Models.Player", b =>
                {
                    b.Property<int>("ID_Players")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Players");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Players"));

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Date_of_birth")
                        .HasColumnType("date");

                    b.Property<int?>("ID_Teams")
                        .HasColumnType("int")
                        .HasColumnName("ID_Teams");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Prize_pool")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Surname")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ID_Players");

                    b.HasIndex("Country");

                    b.HasIndex("ID_Teams");

                    b.HasIndex("Nickname");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Course_Work.Models.PlayersGames", b =>
                {
                    b.Property<int>("ID_Players_Games")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Players_Games");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Players_Games"));

                    b.Property<int>("ID_Games")
                        .HasColumnType("int")
                        .HasColumnName("ID_Games");

                    b.Property<int>("ID_Players")
                        .HasColumnType("int")
                        .HasColumnName("ID_Players");

                    b.HasKey("ID_Players_Games");

                    b.HasIndex("ID_Games");

                    b.HasIndex("ID_Players");

                    b.ToTable("Players_Games");
                });

            modelBuilder.Entity("Course_Work.Models.Team", b =>
                {
                    b.Property<int>("ID_Teams")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Teams");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Teams"));

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Founded_year")
                        .HasColumnType("int");

                    b.Property<int?>("ID_Tournament")
                        .HasColumnType("int")
                        .HasColumnName("ID_Tournament");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Prize_pool")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_Teams");

                    b.HasIndex("ID_Tournament");

                    b.HasIndex("Name");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Course_Work.Models.Tournament", b =>
                {
                    b.Property<int>("ID_Tournament")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Tournament");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Tournament"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("End_date")
                        .HasColumnType("date");

                    b.Property<string>("Location_of_the_event")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal?>("Prize_pool")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Start_date")
                        .HasColumnType("date");

                    b.HasKey("ID_Tournament");

                    b.HasIndex("Start_date");

                    b.ToTable("Tournament");
                });

            modelBuilder.Entity("Course_Work.Models.GamesNews", b =>
                {
                    b.HasOne("Course_Work.Models.Game", "Game")
                        .WithMany("GamesNews")
                        .HasForeignKey("ID_Games")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Course_Work.Models.News", "News")
                        .WithMany("GamesNews")
                        .HasForeignKey("ID_News")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("News");
                });

            modelBuilder.Entity("Course_Work.Models.Match", b =>
                {
                    b.HasOne("Course_Work.Models.Tournament", "Tournament")
                        .WithMany("Matches")
                        .HasForeignKey("ID_Tournament")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Course_Work.Models.Player", b =>
                {
                    b.HasOne("Course_Work.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("ID_Teams")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Course_Work.Models.PlayersGames", b =>
                {
                    b.HasOne("Course_Work.Models.Game", "Game")
                        .WithMany("PlayersGames")
                        .HasForeignKey("ID_Games")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Course_Work.Models.Player", "Player")
                        .WithMany("PlayersGames")
                        .HasForeignKey("ID_Players")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Course_Work.Models.Team", b =>
                {
                    b.HasOne("Course_Work.Models.Tournament", "Tournament")
                        .WithMany("Teams")
                        .HasForeignKey("ID_Tournament")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Course_Work.Models.Game", b =>
                {
                    b.Navigation("GamesNews");

                    b.Navigation("PlayersGames");
                });

            modelBuilder.Entity("Course_Work.Models.News", b =>
                {
                    b.Navigation("GamesNews");
                });

            modelBuilder.Entity("Course_Work.Models.Player", b =>
                {
                    b.Navigation("PlayersGames");
                });

            modelBuilder.Entity("Course_Work.Models.Team", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Course_Work.Models.Tournament", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
